[package]
name = "arrowspace"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
smartcore = "*"
ordered-float = "5.0.0"

[dev-dependencies]
criterion = "*"

[lib]
name = "arrowspace"
crate-type = ["rlib"]

[examples]
range-set-blaze = "*"

[workspace]

[[bench]]
name = "lookup_bench"
harness = false

